name: Deploy FastAPI to jquiroz.net

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy and Run FastAPI
      run: |
        ssh -o StrictHostKeyChecking=no laura@jquiroz.net << 'EOF'
          cd /home/laura/proyecto-api/api-productos-fastapi
          git pull origin main
          source /home/laura/bash/ambiente/bin/activate
          pip install -r requeriments.txt || pip install fastapi uvicorn

          fuser -k 3020/tcp || true
          nohup /home/laura/bash/ambiente/bin/uvicorn main:app --host 0.0.0.0 --port 3020 > fastapi.log 2>&1 &
        EOF